FROM prestashop/prestashop:1.6

ARG cert_path
ENV CERT_PATH=$cert_path

ARG cert_key_path
ENV CERT_KEY_PATH=$cert_key_path

RUN apt update && apt install -y vim
RUN sed -i 's/max_execution_time = 30/max_execution_time = 60/g' /usr/local/etc/php/php.ini
COPY apache/default.conf /etc/apache2/sites-available/000-default.conf
COPY apache/ssl-params.conf /etc/apache2/conf-available/ssl-params.conf
COPY apache/default-ssl.conf /etc/apache2/sites-available/default-ssl.conf
RUN a2enmod ssl
RUN a2enmod headers
RUN a2ensite default-ssl
RUN a2enconf ssl-params
