FROM prestashop/prestashop:8.1-apache

ARG cert_path
ENV CERT_PATH=$cert_path

ARG cert_key_path
ENV CERT_KEY_PATH=$cert_key_path

RUN apt update && apt install -y vim

# XDEBUG
RUN pecl install xdebug-3.1.6 \
      && docker-php-ext-enable xdebug
RUN echo zend_extension=/usr/local/lib/php/extensions/no-debug-non-zts-20190902/xdebug.so >> /usr/local/etc/php/php.ini

# APACHE
COPY apache/default.conf /etc/apache2/sites-available/000-default.conf
COPY apache/ssl-params.conf /etc/apache2/conf-available/ssl-params.conf
COPY apache/default-ssl.conf /etc/apache2/sites-available/default-ssl.conf
RUN a2enmod ssl
RUN a2enmod headers
RUN a2ensite default-ssl
RUN a2enconf ssl-params
